services:
  - type: web
    name: ekg-egitim-asistani
    env: python
    buildCommand: |
      pip install -r backend_ai/requirements.txt
      cd frontend_app
      npm install
      npm run build
    startCommand: "cd backend_ai && uvicorn main:app --host 0.0.0.0 --port $PORT"